Entry.class: Entry.java WordLadder.class
	javac Entry.java

WordLadder.class: ./components/WordLadder.java
	javac ./components/WordLadder.java -Xlint:unchecked

clean:
	rm ./components/WordLadder.class Entry.class
